import AuthManager from "@/components/auth/AuthManager";
import ModalManager from "@/components/modals/ModalManager";
import MainSidebar from "@/components/sidebar/MainSidebar";
import StoreProvider from "@/redux/StoreProvider";
import { Metadata } from "next";
import "../globals.css";
// bg-[#161b34]
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fr">
            <body className="text-white bg-[#0f1225]">
                <div className="flex justify-center h-screen max-w-[1500px] mx-auto">
                    <div className="w-72 overflow-y-auto shrink-0 shadow-xl">
                        <MainSidebar />
                    </div>
                    <main className="grow max-h-full overflow-y-auto">
                        {children}
                    </main>
                </div>
                <StoreProvider>
                    <ModalManager />
                    <AuthManager />
                </StoreProvider>
            </body>
        </html>
    );
}
